version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

  backend:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:
      [
        "/opt/conda/envs/snakemake/bin/python",
        "-m",
        "celery",
        "-A",
        "app.main.celery",
        "worker",
        "--loglevel=info",
        "-E",
        "-Q",
        "workflow_task",
      ]
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
