version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cellcraft
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
      - C_FORCE_ROOT=true
    ipc: host
    build:
      context: ./backend
      dockerfile: Dockerfile.dev.celery
    volumes:
      - ./backend:/app
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
