version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8002:8080" # Changed from "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN
    ports:
      - "8000:8000" # Changed from "8000:8000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cellcraft
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb
    ports:
      - "5432:5432" # Changed to an alternate port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Changed to an alternate port
      - "5672:5672" # Changed to an alternate port

  celery:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
      - C_FORCE_ROOT=true
      - TZ=Asia/Seoul
    ipc: host
    build:
      context: ./backend
      dockerfile: Dockerfile.dev.celery
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
      - db
    deploy:
      resources:
        limits:
          cpus: '44'
    restart: always
    command: bash -c "/opt/conda/envs/snakemake/bin/python -m celery -A app.main.celery worker -c 11 -n worker@%h --loglevel=info"
volumes:
  postgres_data: