version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - GITHUB_TOKEN
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cellcraft
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
      - C_FORCE_ROOT=true
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - GITHUB_TOKEN
    command:
      [
        "/opt/conda/envs/snakemake/bin/python",
        "-m",
        "celery",
        "-A",
        "app.main.celery",
        "worker",
        "--loglevel=info",
        "-E",
        "-Q",
        "workflow_task",
      ]
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
