version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8080" # Changed from "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - GITHUB_TOKEN
    ports:
      - "8002:8000" # Changed from "8000:8000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cellcraft
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb
    ports:
      - "5432:5432" # Changed to an alternate port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Changed to an alternate port
      - "5672:5672" # Changed to an alternate port

  celery:
    environment:
      - CONDA_DEFAULT_ENV=snakemake
      - C_FORCE_ROOT=true
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - GITHUB_TOKEN
    command:
      [
        "/opt/conda/envs/snakemake/bin/python",
        "-m",
        "celery",
        "-A",
        "app.main.celery",
        "worker",
        "--loglevel=info",
        "-E",
        "-Q",
        "workflow_task",
      ]
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
      - db
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 8
            capabilities: [gpu, utility]

volumes:
  postgres_data:
