version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"  # Changed from "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"  # Changed from "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cellcraft
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb
    ports:
      - "5433:5432"  # Changed to an alternate port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15673:15672"  # Changed to an alternate port
      - "5673:5672"    # Changed to an alternate port

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["celery", "-A", "app.main.celery", "worker", "--loglevel=info", "-E", "-Q", "workflow_task"]
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
