version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    restart: always
    environment:
      - TZ=Asia/Seoul
      - VUE_APP_BASE_URL=/api

  backend:
    environment:
      - TZ=Asia/Seoul
      - CONDA_DEFAULT_ENV=snakemake
      - TZ=Asia/Seoul
      
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  db:
    image: postgres:15
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: "rabbitmq:management"
    environment:
      - TZ=Asia/Seoul
    expose:
      - "15672"
      - "5672"
    restart: always

  celery:
      environment:
        - CONDA_DEFAULT_ENV=snakemake
        - C_FORCE_ROOT=true
        - TZ=Asia/Seoul
      ipc: host
      build:
        context: ./backend
        dockerfile: Dockerfile.dev.celery
      volumes:
        - ./backend:/app
      depends_on:
        - rabbitmq
        - db
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: "${GPU_COUNT:-all}"  # 사용자가 설정하지 않으면 모든 GPU 사용
                capabilities: [gpu, utility]
      restart: always

volumes:
  postgres_data:
