FROM tiangolo/uvicorn-gunicorn:python3.10

# 시스템 패키지 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    bzip2 \
    git \
    build-essential \
    autoconf \
    automake \
    libtool \
    curl \
    make \
    g++ \
    unzip \
    default-jdk \
    python3-pip \
    python3-dev \
    jq \
    && rm -rf /var/lib/apt/lists/*

    # Micromamba 설치
ENV MAMBA_ROOT_PREFIX=/opt/micromamba
ENV PATH=${MAMBA_ROOT_PREFIX}/bin:$PATH

# ✅ 신뢰성 높은 설치 방식
RUN curl -L https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj -C /usr/local/bin/ --strip-components=1 bin/micromamba

# Conda 환경 구성
COPY environment.yml ./
RUN micromamba create -y -n snakemake -f environment.yml

# Micromamba 환경 PATH 등록
ENV PATH=/opt/micromamba/envs/snakemake/bin:$PATH
ENV CONDA_DEFAULT_ENV=snakemake


# 작업 디렉토리 설정 및 코드 복사
WORKDIR /app
COPY . .

# Celery 실행
CMD ["/opt/micromamba/envs/snakemake/bin/python", "-m", "celery", "-A", "app.main.celery", "worker", "-n", "worker@%h", "--loglevel=info", "-E", "-Q", "workflow_task,plugin_task"]
