# FROM continuumio/miniconda3
# FROM ubuntu:20.04
FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04

# 기본 패키지 및 Miniconda3 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    bzip2 \
    && apt-get update && apt-get install --reinstall -y ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda \
    && rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH /opt/conda/bin:$PATH

WORKDIR /app

COPY environment.yml ./
RUN conda env create -f environment.yml

COPY . .

RUN apt-get update && apt-get install -y git

# Avoid tzdata asking for geographic location
ENV DEBIAN_FRONTEND=noninteractive

# Set up time zone
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

# CUDA Toolkit 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        software-properties-common

ENV PATH /usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/cuda-12.1/compat

# RUN conda install -n snakemake -c conda-forge cupy
RUN /opt/conda/envs/snakemake/bin/pip install cupy-cuda12x

# Jax 설치
RUN /opt/conda/envs/snakemake/bin/pip install --upgrade pip && \
    /opt/conda/envs/snakemake/bin/pip install "jax[cuda11_cudnn86]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

RUN git config --global user.email "min1125@cau.ac.kr"
RUN git config --global user.name "mindongdong"

ARG GITHUB_TOKEN

# Mate 설치
RUN if [ ! -d "mate" ]; then git clone https://${GITHUB_TOKEN}@github.com/cxinsys/mate.git; fi
RUN cd mate && \
    /opt/conda/envs/snakemake/bin/pip install -e .
    # python setup.py install

# FastTENET 설치
RUN if [ ! -d "fasttenet" ]; then git clone https://${GITHUB_TOKEN}@github.com/cxinsys/fasttenet.git; fi
RUN cd fasttenet && \
    /opt/conda/envs/snakemake/bin/pip install -e .
    # python setup.py install

# OpenMPI 설치를 위한 필요한 패키지 설치
RUN apt-get update && apt-get install -y build-essential autoconf automake libtool curl make g++ unzip

# OpenMPI 소스 코드 다운로드
RUN wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.gz

# OpenMPI 압축 해제 및 설치
RUN tar -xzvf openmpi-4.0.5.tar.gz && \
    cd openmpi-4.0.5 && \
    ./configure --prefix=/usr/local/openmpi && \
    make all && \
    make install

# OpenMPI 환경 변수 설정
ENV PATH="/usr/local/openmpi/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/openmpi/lib:${LD_LIBRARY_PATH}"

# JDK 및 Python 개발 헤더 설치
RUN apt-get update && apt-get install -y default-jdk python3-pip python3-dev jq

# JPype 설치
RUN /opt/conda/envs/snakemake/bin/pip install JPype1

# Activate the conda environment and run FastAPI
CMD ["/opt/conda/envs/snakemake/bin/python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0"]

# Create a non-root user
# RUN adduser --disabled-password --gecos '' celeryuser
