FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04

# 필요한 패키지 설치
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    software-properties-common \
    dirmngr \
    wget \
    && wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | gpg --dearmor -o /usr/share/keyrings/r-project.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/r-project.gpg] https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/" | tee /etc/apt/sources.list.d/r-project.list \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    bzip2 \
    git \
    build-essential \
    autoconf \
    automake \
    libtool \
    curl \
    make \
    g++ \
    unzip \
    default-jdk \
    python3-pip \
    python3-dev \
    jq \
    openssh-client \
    r-base \
    r-base-dev \
    # R 패키지 빌드 및 설치에 필요한 시스템 의존성
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    && rm -rf /var/lib/apt/lists/*

# R 패키지 설치를 위한 기본 설정
RUN echo "options(repos = c(CRAN = 'https://cloud.r-project.org/'))" > /usr/lib/R/etc/Rprofile.site

# Miniconda 설치
RUN wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda \
    && rm Miniconda3-latest-Linux-x86_64.sh

# Conda 환경 변수 설정
ENV PATH /opt/conda/bin:$PATH

# OpenMPI 설치
# RUN wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.gz && \
#     tar -xzvf openmpi-4.0.5.tar.gz && \
#     cd openmpi-4.0.5 && \
#     ./configure --prefix=/usr/local/openmpi && \
#     make all && \
#     make install

# OpenMPI 환경 변수 설정
# ENV PATH="/usr/local/openmpi/bin:${PATH}"
# ENV LD_LIBRARY_PATH="/usr/local/openmpi/lib:${LD_LIBRARY_PATH}"

# 작업 디렉토리 설정
WORKDIR /app

# Conda 환경 설정
COPY environment.yml ./
RUN conda env create -f environment.yml


# 애플리케이션 소스 코드 복사
COPY . .

# Celery 애플리케이션 실행
CMD ["/opt/conda/envs/snakemake/bin/python", "-m", "celery", "-A", "app.main.celery", "worker", "-c", "11", "-n", "worker@%h", "--loglevel=info", "-E", "-Q", "workflow_task"]
