"""add_plugin_type_field_to_plugins_table

Revision ID: 696551e16a9a
Revises: ff8810e9f544
Create Date: 2025-08-11 17:29:38.348043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696551e16a9a'
down_revision = 'ff8810e9f544'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    plugintype_enum = sa.Enum('ANALYSIS', 'VISUALIZATION', name='plugintype')
    plugintype_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('plugins', sa.Column('plugin_type', plugintype_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugins', 'plugin_type')
    
    # Drop the enum type
    plugintype_enum = sa.Enum(name='plugintype')
    plugintype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ### 