"""add plugin_image_uri to tasks table

Revision ID: a1b2c3d4e5f6
Revises: ff8810e9f544
Create Date: 2025-01-25 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'ff8810e9f544'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('plugin_image_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'plugin_image_uri')
    # ### end Alembic commands ###