"""add enhanced plugin fields for official/local separation

Revision ID: ff8810e9f544
Revises: 994e0fca8480
Create Date: 2025-07-29 18:22:59.467443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff8810e9f544'
down_revision = '994e0fca8480'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with appropriate defaults for existing data
    op.add_column('plugins', sa.Column('source', sa.String(), nullable=False, server_default='local'))
    op.add_column('plugins', sa.Column('is_editable', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('plugins', sa.Column('version', sa.String(), nullable=True))
    op.add_column('plugins', sa.Column('submodule_path', sa.String(), nullable=True))
    
    # Update timestamp columns to include timezone and ensure they have proper defaults
    op.alter_column('plugins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               server_default=sa.func.now())
    op.alter_column('plugins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               server_default=sa.func.now())
    
    # Remove server defaults after adding columns (keep model defaults)
    op.alter_column('plugins', 'source', server_default=None)
    op.alter_column('plugins', 'is_editable', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugins', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('plugins', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('plugins', 'submodule_path')
    op.drop_column('plugins', 'version')
    op.drop_column('plugins', 'is_editable')
    op.drop_column('plugins', 'source')
    # ### end Alembic commands ### 