import os

rule a1read_data:
    input:
        input="user/{user_name}/data/{input.csv}"
    output:
        output="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/results/output.csv"
    log:
        stdout="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/a1read_data.stdout",
        stderr="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/a1read_data.stderr"
    shell:
        "/opt/conda/envs/snakemake/bin/python /app/plugin/{plugin_name}/scripts/A1.read_data.py {input.input} {output.output} > {log.stdout} 2> {log.stderr}"

rule a2add_column:
    input:
        output="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/results/output.csv"
    output:
        output_add_column="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/results/output_add_column.csv"
    log:
        stdout="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/a2add_column.stdout",
        stderr="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/a2add_column.stderr"
    shell:
        "/opt/conda/envs/snakemake/bin/python /app/plugin/{plugin_name}/scripts/A2.add_columns.py {input.output} {output.output_add_column} > {log.stdout} 2> {log.stderr}"

