# v1.0.7 리팩토링 shim — PR-4에서 제거
from app.core.config import *  # noqa: F401,F403
from app.core.config import (  # noqa: F401
    Settings,
    DevelopmentConfig,
    get_settings,
    route_task,
    settings,
    MAX_UPLOAD_SIZE,
    ALLOWED_EXTENSIONS,
    MAX_FILENAME_LENGTH,
    MAX_FILES_PER_UPLOAD,
    UPLOAD_CHUNK_SIZE,
    SECURITY_LOG_FILE,
    ENABLE_FILE_SIGNATURE_VALIDATION,
    SECURITY_LOG_LEVEL,
    ENABLE_ANOMALY_DETECTION,
    ANOMALY_PATH_TRAVERSAL_THRESHOLD,
    ANOMALY_FILE_SPOOFING_THRESHOLD,
    ANOMALY_USER_EVENTS_THRESHOLD,
    H5AD_COMPRESSION_ENABLED,
    H5AD_COMPRESSION_MIN_SIZE,
)
