name: Deploy on update

on:
  push:
    branches:
      - main  # main 브랜치에 push가 있을 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SSH_KEY }}" > id_ed25519
        chmod 600 id_ed25519

    - name: Debug SSH connection
      run: |
        ssh -vvv -p 10000 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      shell: bash

    - name: Run Docker Compose on remote server
      run: |
        ssh -p 10000 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e  # 명령어 실패 시 즉시 종료
          cd /home/dmshin/cellcraft
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml up -d
        EOF
      shell: bash

    - name: Remove SSH key file
      run: rm -f id_ed25519
